name: Build Go App

on:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build for Linux (amd64)
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/paycoe-linux-amd64 ./...

      - name: Build for Linux (arm64)
        run: |
          GOOS=linux GOARCH=arm64 go build -o bin/paycoe-linux-arm64 ./...

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: go-binaries
          path: bin/

