name: Build Go App

on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Build for Linux (amd64)
        run: |
          GOOS=linux GOARCH=amd64 go build -o bin/paycue-linux-amd64 ./cmd

      - name: Build for Linux (arm64)
        run: |
          GOOS=linux GOARCH=arm64 go build -o bin/paycue-linux-arm64 ./cmd

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: bin/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

